### ISSUE TITLE
[Bug]: Mesure incohérente entre ecoindex et GreenIT analysis et le Network des devtools

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_scrap_python#106]
### What happened?

Ce site https://metyis.com/ est mesuré en `C` avec une page pesant seulement **3 Mo** alors que quand je le charge dans mon navigateur, j'ai au moins **12 Mo de datas**. Qu'est-ce qui fait qu'il passe entre les gouttes ?

https://www.ecoindex.fr/resultat/?id=e274c157-a46f-467f-912a-bbdaf71d166e

GreenIT analysis (j'ai des extensions, donc pas parfait) donne lui un éco index de `D` :

- Request number: 67 | ecoindex 54
- Page Size (KB): 13886 (23674) | ecoindex 3.049
- Dom Size: 452 | ecoindex 464

C'est du Gatsby donc normal d'avoir de bonnes perfs, mais je suis étonné que la vidéo ne le pénalise pas plus et surtout que quasiment **~~10 Mo passe à la trappe~~** quand je scroll en bas de page, j'en suis à **+27 Mo = 30Mo** :slightly_smiling_face:

_Je suis juste avec les extensions, donc la version de python n'est pas importante_

### Version

^3.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Avec le correctif, voilà le nouveau résultat:

```
width=1920 height=1080 url=AnyHttpUrl('https://metyis.com/', ) size=15189.952 nodes=464 requests=54 grade='D' score=53.0 ges=1.94 water=2.91 ecoindex_version='5.4.2' date=datetime.datetime(2023, 5, 16, 17, 39, 37, 784958) page_type='website'
```

Pour info, sur ce site, le nombre de requête est aléatoire: Il charge un fichier data.json en boucle...
