### ISSUE TITLE
[Bug]: Potentially wrong page size value

### ISSUE THREAD

**Issue by tsecher** [cnumr/ecoindex_scrap_python#107]
### What happened?

it seems that the calculated weight of the page is not always consistent. Indeed, currently we add an uncompressed data value to a compressed value. The size page is then possibly different from the values reported by the browser under similar conditions

## Step to reproduce
1. Get the ecoindex for the url https://www.kleegroup.com/fr  (https://www.ecoindex.fr/resultat/?id=3bfab147-c12e-4198-a372-67d77faa9312#score-details) . The size of the page should be around 0.808 Mo 
![image](https://github.com/cnumr/ecoindex_scrap_python/assets/4562067/11d73e57-d2df-4bd4-be87-07df53069dc1)

2. Compare to networks data of chrome browsers in private mode, and after scrolling down the page and waiting few seconds: the size should be around 0.250Mo (compressed), and 0.512Mo (uncompressed)
![image](https://github.com/cnumr/ecoindex_scrap_python/assets/4562067/9f0d865d-f243-49dd-91cc-60baa7fb26f2)

## Expected
According to the specification of the ecoindex, the value should be the total size of transfered data, so the compressed size of the data (in the example around 0.250Mo)

## Notes
We should check if the Network.loadingFinished contains the main page first request. In other tools in NodeJs, it seems that this event is sent on the first page load. In that case, the add of the html size should not be necessary. 

### Version

^3.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
With the fix, here is the result now:
```
width=1920 height=1080 url=AnyHttpUrl('https://www.kleegroup.com/fr', ) size=249.158 nodes=458 requests=40 grade='B' score=71.0 ges=1.58 water=2.37 ecoindex_version='5.4.2' date=datetime.datetime(2023, 5, 16, 17, 20, 36, 488086) page_type='website'
```
