### ISSUE TITLE
Add an option to be compatible with a specific Chrome/Chromium version

### ISSUE THREAD

**Issue by geoffreyarthaud** [cnumr/ecoindex_scrap_python#55]
ecoindex_scrap_python relies on [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) to use the browser. And a chrome driver is specific to a major version of Chrome/Chromium.

undetected-chromedriver has an option `version_main=xx` to set this major version and download/patch the desired version.

It would be great if ecoindex_scrap could allow to set this version : 
- As an environment variable (CHROME_VERSION ?)
- Or auto-detect chrome version, for example with the command `chrome --version`
Today, if the version of Chrome/Chromium is not the latter version of Chrome, this typical error occurs (log from ecoindex_cli) : 

```
cannot connect to chrome at 127.0.0.1:36697
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 107.0.5304.121
```

I'm using Chromium with flatpak, whose version is not exactly synced with last version of Chrome.

Many thanks for this project ! :+1:

**Comment by vvatelot** [comment]
**🙏🏻 Praise:** Thank you for your contribution @geoffreyarthaud ! I greatly appreciate it, moreover this request is really interesting and could help me with a problem I have on production ! I try to implement this quickly. Do you have a documentation somewhere or a clue on how to implement it ?

**Comment by geoffreyarthaud** [comment]
From [undetected-chromedriver README](https://github.com/ultrafunkamsterdam/undetected-chromedriver), you could specify the version like this : 
```
# use specific (older) version
driver = uc.Chrome(options=options, version_main=94)  # version_main allows to specify your chrome version instead of following chrome global version
```
I see the driver initialization in [scrap.py](https://github.com/cnumr/ecoindex_scrap_python/blob/35fe2d0075b03b8d0268e1eefe971df3fcb5f510/ecoindex_scraper/scrap.py#L53)

To get the version of chrome, one need to parse the result of this command : 
```
> chrome --version
Chromium 107.0.5304.121 
```
to get the main version 107 here.

I guess I could make a PR soon, if you accept contributions.

**Comment by vvatelot** [comment]
@geoffreyarthaud I totaly accept contributions ! If you have time to do it, be my guest ! 🙂

**Comment by vvatelot** [comment]
Hello @geoffreyarthaud your idea was so great and I need to go fast (I have erratic behaviour with the ecoindex API in production because of this !) so I made a PR. "On my laptop" it works... And yours ?

**Comment by geoffreyarthaud** [comment]
Hello @vvatelot !

I think It should be ok. I directly use ecoindex_cli for now. I think a future version [ecoindex_cli](https://github.com/cnumr/ecoindex_cli) could automatically detect the version of Chrome and use this evolution.

Good job ! Thanks !
